# Generated by Django 3.2 on 2021-05-19 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_order_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='additionalExpenses',
        ),
    ]
