# Generated by Django 3.2 on 2021-05-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20210522_0539'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.CharField(default=7, editable=False, max_length=100),
            preserve_default=False,
        ),
    ]
