# Generated by Django 3.2 on 2021-05-06 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Raw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('materialType', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=0, max_digits=100)),
                ('unitType', models.CharField(max_length=200)),
                ('totalCost', models.DecimalField(decimal_places=2, max_digits=100)),
            ],
        ),
    ]
