# Generated by Django 3.2 on 2021-05-31 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw', '0006_initialpr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initialpr',
            name='unitType',
            field=models.CharField(choices=[('Packing', (('pc', 'Piece'), ('6pack', '6-Pack'), ('dozen', 'Dozen'))), ('Volume', (('tsp', 'Teaspoon'), ('tbsp', 'Tablespoon'), ('cup', 'Cup'), ('pt', 'pint'), ('qt', 'Quart'), ('gal', 'Gallon'), ('ml', 'Milliliter'), ('liter', 'Liter'))), ('Weight', (('lb', 'Pound'), ('oz', 'Ounce'), ('mg', 'Milligram'), ('gram', 'Gram'), ('kg', 'Kilogram'))), ('Length', (('in', 'Inch'), ('ft', 'Feet'), ('yd', 'Yard'), ('mm', 'Millimeter'), ('cm', 'Centimeter'), ('meter', 'Meter')))], max_length=200),
        ),
    ]
