# Generated by Django 3.2 on 2021-05-23 15:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InitialTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('customerName', models.CharField(max_length=200)),
                ('contactInfo', models.CharField(max_length=20)),
                ('shippingLocation', models.CharField(max_length=200)),
                ('courier', models.CharField(max_length=50)),
                ('shippingRef', models.CharField(max_length=50)),
                ('additionalExpenses', models.DecimalField(decimal_places=2, max_digits=100)),
                ('notes', models.CharField(blank=True, max_length=100)),
                ('user', models.CharField(editable=False, max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
