# Generated by Django 3.2 on 2021-05-30 07:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20210524_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='QuantityTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('trans', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.ordertwo')),
            ],
        ),
        migrations.DeleteModel(
            name='Initial',
        ),
        migrations.AlterField(
            model_name='initialtwo',
            name='products',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.ordertwo'),
        ),
        migrations.AlterField(
            model_name='initialtwo',
            name='quantity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.quantitytwo'),
        ),
    ]
