# Generated by Django 3.2 on 2021-05-30 07:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20210530_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initialtwo',
            name='quantity',
            field=models.PositiveIntegerField(default=9, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='QuantityTwo',
        ),
    ]
