# Generated by Django 3.1.7 on 2021-05-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_trial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Initial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('itemType', models.CharField(max_length=200)),
                ('sellPrice', models.DecimalField(decimal_places=2, max_digits=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Trial',
        ),
    ]
